### ISSUE TITLE
State Changes on Client

### ISSUE THREAD

**Issue by ericclemmons** [ericclemmons/react-resolver#1]

**Comment by aaronshaf** [comment]
Is this concern similar to that of the setup/teardown on https://github.com/ryanflorence/react-router-async-props ?

**Comment by ericclemmons** [comment]
I... don't think so?  This is just to ensure that any unresolved dependencies in child components are resolved when the state changes.

**Comment by ericclemmons** [comment]
Ok, making state changes causes a re-render and works just fine on the client!

Color me surprised!  Time to take this baby for a test-drive with a live project! :D
