### ISSUE TITLE
Can I use this without server rendering?

### ISSUE THREAD

**Issue by adriaanbalt** [ericclemmons/react-resolver#102]
I'm curious if I can use this tool but not isomorphic server rendering?  Just building a regular React app with API requests.  Thanks

**Comment by ericclemmons** [comment]
Yep!

> http://ericclemmons.com/react-resolver/docs/getting-started/ClientRendering.html

Still need to update everything for the latest tech (since React Router 2 has launched & what-not).

**Comment by adriaanbalt** [comment]
Thanks Eric, I was able to figure it out.  Great tool!  Now I'm trying to implement a Loader around the data loading.  Can you recommend a way in which I would go about doing this?

**Comment by ericclemmons** [comment]
I personally use Axios for AJAX requests, while letting React Router handle
the rest. This causes any state changes to happen purely through routes.

If you're using something like Redux, this library currently isn't a good
fit.

On Tue, Feb 2, 2016 at 11:43 AM Adriaan Balt Louis Schölvinck <
notifications@github.com> wrote:

> Thanks Eric, I was able to figure it out. Great tool! Now I'm trying to
> implement a Loader around the data loading. Can you recommend a way in
> which I would go about doing this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ericclemmons/react-resolver/issues/102#issuecomment-178709059>
> .
>
-- 
- Eric Clemmons
