### ISSUE TITLE
Support variable?

### ISSUE THREAD

**Issue by gutenye** [ericclemmons/react-resolver#115]
For pagination, need to re-fetch the data when click next page.  

Does it support variable for this feature?

**Comment by ericclemmons** [comment]
Good question.  In this scenario, I updated the route with `?pg=2` or similar, which caused the re-render.

I _believe_ I had to force re-render on query string changes though...

**Comment by monder** [comment]
I'm using `react-router` for route handling, and it works just by pushing the qs to the route. No force re-render necessary.

**Comment by ericclemmons** [comment]
@monder's solution is ideal, especially with react.  React Resolver does a great job of loading data as the tree renders, but re-rendering should be triggered somewhere further up the tree by URL or by another component.
