### ISSUE TITLE
Unhandled rejections server side

### ISSUE THREAD

**Issue by ekmartin** [ericclemmons/react-resolver#116]
Hi!
It seems like resolver errors bubbles up, even if they're caught like in the example [here](https://github.com/ericclemmons/react-resolver/blob/master/examples/react-v0.14/src/app.js#L48-L50).

Example:
```js
process.on('unhandledRejection', function() {
  console.log('Unhandled rejection', arguments);
});
```

The errors are still handled by the catch-clause in app.js, but they bubble up to the process handler nonetheless.

**Comment by monder** [comment]
Any luck with that?
I'm trying to implement a proper error handling on both server and client side, but currently with no success.
