### ISSUE TITLE
Documentation links are broken

### ISSUE THREAD

**Issue by sedubois** [ericclemmons/react-resolver#120]
Hi, I'd like to know if this project is still maintained? It looks promising and I'm looking forward to try it out.

But the first thing I notice is that various documentation links seem not to be working. For example http://ericclemmons.com/react-resolver/ has a link in the Documentation section to http://ericclemmons.com/react-resolver/docs/getting-started/, but it does not work (404). Actually, the three categories "Introduction", "Getting Started", "API Reference" and "Troubleshooting" seem to be missing links, whereas their sub-categories work (but "Troubleshooting" does not have any sub-category).

**Comment by sedubois** [comment]
There are also entries "Universal Architecture" and "Similar Projects" in the left-side navigation, which cannot be clicked. However, there is an arrow at the bottom of the "Motivation" page, http://ericclemmons.com/react-resolver/docs/inroduction/UniversalArchitecture.md, but this also resolves to 404.

**Comment by monder** [comment]
Hmm. The documentation is auto generated from github `.md` files.

The initial page - http://ericclemmons.com/react-resolver/ - is the same as https://github.com/ericclemmons/react-resolver.
http://ericclemmons.com/react-resolver/docs/getting-started/ is actually https://github.com/ericclemmons/react-resolver/tree/master/docs/getting-started.

I'll think of something to fix relative links here.

**Comment by monder** [comment]
Fixed.

**Comment by sedubois** [comment]
Thanks :)
