### ISSUE TITLE
Breakage with React 16: PropTypes no longer exported by React

### ISSUE THREAD

**Issue by thirdhand** [ericclemmons/react-resolver#131]
This library breaks with React 16 because PropTypes no longer is exported by React, but must be added as it's own [dependency](https://www.npmjs.com/package/prop-types).

**Comment by pwmckenna** [comment]
https://github.com/ericclemmons/react-resolver/pull/127 shipped with 3.1.1. Should be good to go. Any more known issues with React 16?
