### ISSUE TITLE
Idea: remove lodash dependency

### ISSUE THREAD

**Issue by goatslacker** [ericclemmons/react-resolver#14]
In an effort to reduce library size and dependencies lodash is a good candidate for removal.

You can get away with using ES5 for most of your lodash uses, for the rest perhaps you can include the lodash single function from npm.

**Comment by ericclemmons** [comment]
:+1:

**Comment by ericclemmons** [comment]
Solved via [v1.0.0](d7c9d843e091700f0c3f61843f8f3e8bfd707f64).
