### ISSUE TITLE
Not resolving again when transitioning to sibling state

### ISSUE THREAD

**Issue by bioball** [ericclemmons/react-resolver#17]
Hey, there, I feel like I must be missing something obvious, but I'm not sure where. Why isn't the resolving running when I transition into a sibling state? How should this be done correctly?

Created a repo to demonstrate:

https://github.com/bioball/react-router-test

**Comment by ericclemmons** [comment]
@bioball First, thank you _so_ much for the example.

This is indeed a bug that can be resolved!

I recorded a video showing how it works upon reload, and not as you expected:
> ![bug](https://cloud.githubusercontent.com/assets/15182/6733107/f9f1ce14-ce1d-11e4-8f1d-8d810fe51da5.gif)

**Comment by ericclemmons** [comment]
Fixed via #33 & `v1.1.6`!

**Comment by bioball** [comment]
Sweet!
