### ISSUE TITLE
Error handling with async resolution

### ISSUE THREAD

**Issue by jesseskinner** [ericclemmons/react-resolver#2]
Hey awesome to be collaborating. react-resolver and solve have a different syntax for callbacks, so we should consider which syntax to use.

solve doesn't use node-style callbacks (function(error, data)). My thinking here is that if data is being resolved as an object or arrays etc., then only a single value can be emitted from an async resolution, so the callback only takes a single argument. So error handling has to be somehow resolved into the props object.

One option might be to have multiple types on a single data point, eg.

```javascript
{ 
    value: function(done) {
       request.get('/api/data', function(error, result) {
            if (error) {
                return done(new Error("Failed to load"));
            }
            return done(result);
       });
    }
}

// later in render
if (this.props.value instanceof Error) {
    return <Error error={this.props.value} />;
}
// otherwise
return <Component value={this.props.value} />;
```

another option might be to resolve to multiple properties of an object, eg.

```javascript
{ 
    value: function(done) {
       request.get('/api/data', function(error, result) {
            if (error) {
                return done({ error: new Error("Failed to load"), data: null });
            }
            return done({ error: null, data: result });
       });
    }
}

// later in render
if (this.props.value.error !== null) {
    return <Error error={this.props.value.error} />;
}
// otherwise
return <Component value={this.props.value.data} />;
```

Thoughts on this? Do you think the node/async (error, data) callback syntax is important to maintain? Or do you agree that it make sense to force the user to think about how to translate the errors into a props object in a more deliberate way?

**Comment by ericclemmons** [comment]
I normally use Promises (gasp!), but opted to support node-style callbacks for easy Isomorphic support in the examples.

Perhaps the question should be:
> Who handles the errors & how?

I think you're right with preferring `done(value)` for callbacks, especially to integrate `solve`.

I very much like the idea of thrown errors (e.g. an `ApiService` gets a 500) being available for the UI to answer.

For example, suppose you're in a <Mail.Messages /> component that lazy-loads `this.props.messages`.  If that fails, you'd want to render something like _"Whoops!  I couldn't get messages from the server. <Retry>?"_.

The question is, **what in the component do we check to render this error**?

Here's my proposal for the new API:

- Dynamic props should (somehow) have the equivalent `propTypes` checks.
  - If the prop is required (e.g. `React.PropTypes.any.isRequired`), then the `render()` is neutered (like it is currently) until the props are resolved
  - If the prop is optional (e.g. `React.PropTypes.any`), then it's expected the `render()` knows how to handle missing props by displaying _Loading..._ or something.
- Dynamic props return a promise or call `done(value)`, where `this.props.myProp = value;`.
- Any thrown errors will be caught by `Resolver.mixin` (or the `this.context.resolver` instance)
  - Errors _could_ be available via `this.context.resolver.errors`.
  - The user _could_ provide an `onError` callback for the `new Resolver({ ... })` that gets called when any error occurs during resolution.
  - Errors _could_ be handled via `resolver.handle(Handler).catch(...)` on the server.
  - Should errors be emitted for listeners to pick up on? (e.g. `resolver.emit('error', { .. })`) 

As I created this project to encourage testability (by testing `<Mail.Messages messages={...} />` on the server, and the client lazy-loading `messages` into `<Mail.Messages />`), the ideal solution would be something where we can test `<Mail.Messages />` when it gets an error.  Perhaps means mocking the failed service?  But that seems like a coupling code-smell compared...

Back to you @jesseskinner!

**Comment by jesseskinner** [comment]
I like the idea of using `propTypes` to know when it's safe to render. Couldn't it use the actual `propTypes` on the component, rather than something that is the "equivalent of `propTypes`"?

This sounds good:

> Dynamic props return a promise or call done(value), where this.props.myProp = value;.

For errors not caught within the statics definition, or that should be handled globally, I think this makes a lot of sense:

> Errors could be handled via resolver.handle(Handler).catch(...) on the server.

If users want the errors to be available as props, they could use the mechanisms I described above to catch the errors as they happen, and use the done callback to expose them as part of the prop resolution.

So this would give users two ways to handle errors - inline (via callback or promises), and globally (via handler catch), and without adding new API to react-resolver. So the event handling of an `onError` callback is probably superfluous, because it can be done by the user themselves with code in the `catch`.

Regarding this suggestion:

> Errors could be available via this.context.resolver.errors.

I think we should avoid introducing a third pathway for data, there are already `props` and `state` so having users access stuff on `context` is probably unnecessary. Also, I believe `context` is undocumented and might likely change in the future.

**Comment by jesseskinner** [comment]
Just had a thought. Callbacks could support both mechanisms via arguments.length, whether there is one argument - done(result) - or two - done(error, result).

**Comment by ericclemmons** [comment]
-[ ] Does `throw new Error(...)` get caught/wrapped by Bluebird?

**Comment by jesseskinner** [comment]
I haven't used Bluebird but the standard with Promises is that any errors thrown inside the promise handler or then callbacks will result in a failed promise and the error being passed to any catch callbacks.

**Comment by ericclemmons** [comment]
Note to self:

- [ ] Test cases for when errors are thrown
- [ ] Recommendation in the docs on how this is handled
- [ ] Discussion on if `React.PropTypes.isRequired` should be a pivot for bubbling up errors or trapping them

**Comment by ericclemmons** [comment]
Cleaning up issues.  v2 is a complete re-write that's in production, and it's best to deal with any new architecture updates post-launch.

Still want to continue collaborating, and having seen performance issues with ES6 Promises, callbacks _will_ be coming back!
