### ISSUE TITLE
Bootstrap client-side data

### ISSUE THREAD

**Issue by ericclemmons** [ericclemmons/react-resolver#22]
- Need to expose `resolver.states` for serialization and output on the server.
- Client needs to bootstrap `new Resolver(window.__resolver__)` or something .

**Comment by iamdustan** [comment]
Do you expect this entire process to be a part of react-resolver or just something that Resolver exposes ?

**Comment by ericclemmons** [comment]
I'm... not sure what you mean.  Do you mean, "will there be a way to custom serialize/deserialize" data?

**Comment by iamdustan** [comment]
Potentially it would’ve been better to ask how you foresee this coming to fruition.

Currently the `renderToString` method resolves to `Resolver.renderToString(<Component />).then((string) => ...);`

Is the expectation that this will instead resolve to:

```javascript
Resolver.renderToString(<Component />).then((result: {html: String; data: Object}) => ...);`
```

**Comment by ericclemmons** [comment]
Ooh, I see now.  Right, I was considering either returning an object like you mentioned, or letting the user do something like:

```javascript
const resolver = new Resolver();

resolver.renderToString(<Component />).then((result) => {
  const serialized = resolver.serialize();
  ...
});
```

**Comment by iamdustan** [comment]
Ah. Yeah, custom serialization could be really useful.

I just put together a quick PR to show you what I was thinking. I suspect the more interesting part of this will be having the client rehydrate itself. Also, that PR is a breaking change since the `.then()` becomes an object.

Oh! I could probably hack it to be backwords compatible with a custom `toString()` function that returns the html!

**Comment by ericclemmons** [comment]
Yea, that's why I was curious about changing the signature for those static methods.

I kinda envisioned them being the "dumb" methods, since I'd expect _most_ people to have some Flux implementation that they'd be serializing separately, like with Alt.

I even considered having a slightly different version as `IsoResolver` that would extends `Resolver` that could change the signature w/o a BC break.

@iamdustan Any concerns about serialization?  I'd hope that custom serializers are an edge case...

**Comment by iamdustan** [comment]
What would it look like to push off rehydration to a flux Store or something similar? Something I’m interested in exploring is implementing a Relay-like store for this.

A global `ResolverStore` that manages rehydration of the client/server boundary. Having this be pluggable for custom serializers may be useful/needed?

**Comment by ericclemmons** [comment]
I figured Store hydration was outside the scope of this project and removed the need to hydrate the `Resolver`'s state at all.

This could probably be tested with `Alt` + `Iso`.

Internally, there is `resolver.state = { ... }` that houses the async data for a sync `React.render*` on the 2nd pass.  This _could_ warrant being a `ResolverStore` instance.

I was always concerned with introducing Flux nomenclature since there are so many implementations and it wouldn't necessarily be "listenable" by other libraries =(

**Comment by iamdustan** [comment]
I am interested in two directions (neither of which I have much experience with).

1. `react-router` has internal stores and actions hidden that I believer are hidden from the consumer. Could a similar approach work here?
2. Could there be an adapter or `inject` function for using any `Store`? We provide a default `ResolverStore` with an `inject` method to override with your own.

**Comment by jasonphillips** [comment]
Have you checked out the approach of `react-transmit`?  I haven't developed with that package just yet, but I saw that it does at least promise an implementation of server-side rendering with injection of data into page markup.

Documentation of data injection:
https://github.com/RickWong/react-transmit/blob/master/DOCS.md#injectintomarkuphtml-data-scripts--string

Example usage on server:
https://github.com/RickWong/react-isomorphic-starterkit/blob/2bf29c747770e79de06e130af325e0bdfb216bc9/src/server.js#L52

**Comment by ericclemmons** [comment]
I haven't looked into `react-transmit`'s solution.  Thanks for the links!  I'll check it out to see what's being used internally in that project.

In this one, there's an empty `{}` object that acts as the state holder that I was going to serialize and lookup via `window.__REACT_RESOLVER__`, if on the client.

**Comment by ericclemmons** [comment]
This is being handled in #34.
