### ISSUE TITLE
Aborting transition for failing promises / requests

### ISSUE THREAD

**Issue by srph** [ericclemmons/react-resolver#23]
Question -- does this has to be done manually?

**Comment by ericclemmons** [comment]
My guess is yes, but I'm not 100% sure what you mean.  Are you talking about with React Router using `willTransitionTo`, and aborting if a promise doesn't resolve?

I still need to figure out what to do when promises fail, so maybe this is a good test-case.

A little more detail would be greatly appreciated!

**Comment by srph** [comment]
Yea, I am referring to `willTransitionTo`. I don't think there would more deeper details, because it's just the usual *hey-an-exception-was-thrown-or-maybe-400-or-500-occured-let's-stop-going-to-this-route* thing, like in Angular. I'd like to have them by default with some util or something.

**Comment by srph** [comment]
In regards to 400, it should be handled by a middleware component (or mixin). The only thing we should be handling, I think, are 500 errors.

**Comment by jesseskinner** [comment]
@srph Since react-resolver only deals with promises, not Ajax requests or HTTP errors, it should probably be up to the promises (or whichever library is doing the Ajax calls) to determine whether to resolve or reject based on the HTTP response.

There's still an open question here about error handling, I think, regardless of what is causing the errors.

**Comment by ericclemmons** [comment]
I agree.

I think it's _highly_ project-specific, but I definitely see validity in being able to do something like:

```javascript
Resolver.createContainer(Users, {
  onError: function(error, props, context) { 
    context.router.go(`/error/user?code=404&userId=${props.userId}`)
  resolve: { ... }
});

Alternatively, on the server, if you do `Resolver.renderToString(...).catch()`, you can choose to render an error view instead (effectively a 400 or 500).

To add more fuel to the fire, I was _also_ considering still rendering the view, as long as the `.propTypes` are not `.isRequired`, and let the child component deal with the missing data.  Or, perhaps send an `errors` prop to the view.

Let's continue the discussion in #2, since @jesseskinner foreshadowed this problem in the beginning :)
