### ISSUE TITLE
Aborting promise

### ISSUE THREAD

**Issue by srph** [ericclemmons/react-resolver#25]
Anybody have ideas how to abort the promise from route A from resolving when I transition to route B while the promise hasn't been resolved yet?

To further illustrate this (I find my explanation a bit confusing), given that this is the normal flow:
`transition to route A -> run route A promise -> [waiting.. do anything ] -> resolve`

And if I try to go to route B, I expect:
`transition to route A -> run route A promise -> go to route B -> abort route A promise -> run route B promise`

What happens is:
`transition to route A -> run route A promise -> go to route B -> [route A promise may resolve here] run route B promise -> [route A promise may resolve here] resolve route B promise`.

route A's promise should be aborted like Angular. Any thoughts in this? Thanks.

**Comment by ericclemmons** [comment]
The promise spec, AFAIK, doesn't support aborting.  Are your questions more centric to react router, or information being resolved with this project?

If you load `<Users />`, that information will be fetched and resolved.  While this is happening, if you navigate instead to `<User id="123" />`, the original promise will still complete, as will the current one.

**Comment by srph** [comment]
I see. Makes sense. Thanks!
