### ISSUE TITLE
A callback interface

### ISSUE THREAD

**Issue by goatslacker** [ericclemmons/react-resolver#35]
Promises are nice but I like flexibility, can we have a react-resolver core and then we choose whether we want promises, callbacks, generators, thunks, or whatever emerges next.

**Comment by ericclemmons** [comment]
Do you mean a Promise-free version (top to bottom), or you'd like the ability to do node-style callback resolution in the `resolve` block?

The internals are doing a `Promise.all`, so there would need to be some core equivalency here, whether with an outside dependency (`async`?) or similar...

**Comment by goatslacker** [comment]
Top to bottom would be nice but that's just a pipe dream. Just the ability to do callbacks or whatever in the resolve block is a good start. 

Yeah you would need async.parallel

**Comment by ericclemmons** [comment]
I can pretty easily add back in callback support in the `resolve` block based on the arity (is that the right word?) of the function.

Behind the scenes, it'll use a Promise to map it.

Is that ok for now?

I didn't know if Promises should be avoided in your estimation, or what?

**Comment by goatslacker** [comment]
No it's not necessary to avoid them. As long as resolver isn't swallowing errors promises are great.

**Comment by ericclemmons** [comment]
I... guess we're fine then?  I do know it's recommended to do `Resolver.renderSomehow(...).catch(...)`, since it's promise-driven.

**Comment by srph** [comment]
I like the idea as well. I'm starting to like generators recently.

**Comment by goatslacker** [comment]
Pseudo-code:

```js
// where you resolve the promises:
return new Promise((resolve, reject) => {
  // create a node-style callback
  const callback = (err, value) => err ? reject(err) : resolve(value);

  // call the resolve prop
  const value = resolveProp(props, context, callback);

  // if a Promise is returned then attach to it.
  if (value && value.then && typeof value.then === 'function') {
    value.then(resolve).catch(reject)
  }
})
```

**Comment by ericclemmons** [comment]
Ahhhh, that takes me back :)
> https://github.com/ericclemmons/react-resolver/blob/b7a46a169a88c0a083b6ed6789eb94465d684e25/src/mixin.js#L48-L54

That was a simpler time!

Nice code, BTW.  That solves it pretty well.

Now I'm curious.  I guess I still use promises wrong??
> https://github.com/petkaantonov/bluebird/wiki/Promise-anti-patterns#the-thensuccess-fail-anti-pattern

**Comment by goatslacker** [comment]
I think if you return the promise itself you'll be a-ok since it'll unwrap itself. I'm probably doing it wrong.

**Comment by ericclemmons** [comment]
Oh no, I think you're right.  In one of the other issues, I opted for `.then(resolved, rejected)`, whereas I should've just used `.then(resolved).catch(errored)`.

**Comment by ericclemmons** [comment]
v2 is a complete-rewrap & will support decorators & a better mechanism with dealing with errors.

TBH, callbacks are soooo great for error states :)  Closing to start fresh post-v2...
