### ISSUE TITLE
why markup different on server and client

### ISSUE THREAD

**Issue by gilesbradshaw** [ericclemmons/react-resolver#47]
any pointers as to how I could debug this?

Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) <noscript data-reacti
 (server) <div data-reactid=".1

**Comment by ericclemmons** [comment]
@gilesbradshaw Yes, I can work up a solution for you on this.

**Comment by gilesbradshaw** [comment]
I'm slightly confused..  This is my component - 
````
    export var YoAlt = Resolver.createContainer(InnerComponent, {
  resolve: {
    linkName:()=>"APPPPPP",
    link:()=>'app1',  
    list: (props, context)=> 
     new Promise(
        resolve=>
          setTimeout(
            (()=>
              resolve(new List([{id:0,content:"ahhhh"}]))
              ),
            1000)
        )
  }
});
````



so it gets rendered on the server fine with Resolver.renderToString  Then downloaded to the client then the warning is raised because the client renders <noscript data-reacti &c. - until it resolves the promise.  Surely as the server has already resolved the promise the client doesn't have to as well and should just accept what the server sent until something else happens?  Why is the promise being resolved on the client at all?

**Comment by gilesbradshaw** [comment]
I am a little confused.  The server has rendered the markup - having made the asynchronous call.  The client then also makes the asynchronous call - after having done it's render.  Surely the point is that the call has been made on the server so it doesn't need to be re made by the client?  Ie the client should just accept the markup from the server.

**Comment by gilesbradshaw** [comment]
my project is here btw - wld be  grateful if you could have a look!  

http://localhost:7000/app2 brings up the warning + does async calls on both server + client

**Comment by iamdustan** [comment]
@gilesbradshaw we’ve been using this PR for all of our isomorphic projects of late: https://github.com/ericclemmons/react-resolver/pull/34

Basically, you have to tell react-resolver that the call has already been made and put that data into memory (not just into markup).

**Comment by gilesbradshaw** [comment]
I wish I understood that @iamdustan - could you very kindly explain further?

**Comment by gilesbradshaw** [comment]
I have made a script on the serer which says
````
<script async>var __resolver__ = {".0":{"fulfilled":true,"rejected":false,"values":{}},".0.0":{"fulfilled":true,"rejected":false,"values":{"linkName":"APPPPPP","link":"app1","list":[{"id":0,"content":"ahhhh"}]}}};</script><script src="http://localhost:7001/assets/main-33d5ca2650f97c3b76c5.js"></script><script src="http://localhost:7001/assets/0.7bb83fb274f8d7d75a21.hot-update.js"></script>

````

now I need to rehydrate that on the client not sure how though!  :)

**Comment by ericclemmons** [comment]
@gilesbradshaw Sorry this isn't public API yet!

You can instantiate a `const hydratedResolver = new Resolver(window.__resolver__)` on the client;

> https://github.com/ericclemmons/react-resolver/blob/0aa36afc7e694550592c09f19e197917677b6739/src/Resolver.js#L7-L11

And pass it in to `Resolver.render` via:
```js
Resolver.render(<Handler />, document.getElementById("app"), hydratedResolver);
```

> https://github.com/ericclemmons/react-resolver/blob/0aa36afc7e694550592c09f19e197917677b6739/src/Resolver.js#L161-L169

```

That _should_ work!

**Comment by gilesbradshaw** [comment]
got it!  - actually I just did new Resolver(0 - it defaults to __resolver__ at least in what I have - but passing __resolver__ (or whatever) to Resolver makes sense.

Really pleased about that :)

I assume now __resolver__ can be the whole tree of fetched data from the server. + also hopefully some of the data can not be fetched on the server  and would then be fetched by the client.

**Comment by ericclemmons** [comment]
@gilesbradshaw Right.  When rendering on the server, you should be able to do something like `window.__resolver__ = JSON.stringify(resolver.states);` to get the history.

Whatever comes back is all that's necessary to recreate the entire tree for initial load, then work as normal thereafter!

**Comment by ericclemmons** [comment]
Alright, so this is entirely solved in v2.  Closing in favor of that...
