### ISSUE TITLE
How does this fit in with flux?

### ISSUE THREAD

**Issue by gilesbradshaw** [ericclemmons/react-resolver#49]
My impression is that 'isomorphic' flux implementations tend to associate data fetching requirements with the router which imo is the wrong place - they should be associated with components - so I can change the set of components displayed on a route - or indeed in an app without routing and the data requirements change.

Whereas react-resolver is associating data requirements with the components.  My question is (if this makes sense) can the two be combined to make a flux architecture which  recursively loads data on the serer and client ar react-resolver does + data requirements are defined by components themselves.  I *think* this is what https://www.npmjs.com/package/react-nexus might be but I didn't get it to work.

What I am thinking is that the promises configured by the resolve parameter could trigger actions and wait for store results something like:

````
Resolver.createContainer(InnerComponent, { 
    resolve:
        {
            data:async (props,context)=>{
                await context.flux.getActions("data-action").goGetData(props.id);
                return context.flux.getStore("data-store").getData();
            }
        }
  }
````

I am also thinking you could have isomorphic forms...
````
Resolver.createContainer(InnerComponent, { 
    resolve:
        {
            data:async (props,context)=>{
                await context.flux.getActions("data-action").goPostData(props.id);
                return context.flux.getStore("data-store").getAcknowledgement();
             }
        }
  }
````

**Comment by srph** [comment]
I'm a bit confused. Anyway, in my case, I just hydrate the stores through actions with what the components fetch.

```es6
Resolve.createContainer(UsersListContainer, {
  resolve: {
    data() {
      return WebAPIUtil.somePromise()
        .then((res) => { UserActions.hydrate(res.data); return res; });
    }
  }
});
```

**Comment by ericclemmons** [comment]
There's a custom flux implementation that this works with, but for v1, a great way to work with flux is something like:

```
@someFluxConnector((dispatcher) => dispatcher)
@Resolver.resolve({
  resolve: {
    user: function({ dispatcher}) {
      return dispatcher.stores.User.findById(1) || dispatcher.actions.User.fetchById(1);
    },
  },
})
```
