### ISSUE TITLE
Clarify if a mixin is needed

### ISSUE THREAD

**Issue by adri** [ericclemmons/react-resolver#5]
From the usage description in the readme it seems like there is no mixin needed, but the examples use the `Resolver.mixin`. In my tests the `resolve` callbacks are not called without the mixin. 

Is there a way to use react-resolver without any mixins? If not it would be nice to mention that in the readme.

**Comment by ericclemmons** [comment]
Oh my goodness, you're right!  The mixin is required for both server & client-side rendering.

Thanks!
