### ISSUE TITLE
React Transmit

### ISSUE THREAD

**Issue by ericclemmons** [ericclemmons/react-resolver#50]
Though this project (which started internally @ work) was made public a [couple months][1] before @RickWong's [`react-transmit`][transmit]'s [initial commit][2], Transmit's comparison to Relay, React Native support, and continued development looks like it may have superseded this project.

Our goals are similar, although with `v1` I dropped the comparisons to Relay, since lack of GraphQL made the comparison to Relay tenuous at best, in my opinion.  Really, this project's goals were always to support isomorphic lazy-loading of data, primarily for work.

I've continued development of this project internally, since a major relaunch @ work greatly depends on this (there's even a sibling Flux implementation that gets around dispatcher issues), but I'm curious if it's best to let @RickWong's project be endorsed rather than risk fragmentation, stagnation of this project, or competing over the same problems.

I've tagged @RickWong several times, mainly to get his feedback :)

[1]: https://github.com/ericclemmons/react-resolver/commit/82fd88d18ec705185d30e4bfdde3ce1eda0071b1
[2]: https://github.com/RickWong/react-transmit/commit/5e26a437996c1a9673fd8b3e2b4d2304da450040
[transmit]: https://github.com/RickWong/react-transmit/

**Comment by gilesbradshaw** [comment]
noooo am just getting into it!  :P

**Comment by ericclemmons** [comment]
Hahah, no worries @gilesbradshaw :)  It works great, and has more features + fixes getting prepped for release in June.

The question popped up in other channels, so I wanted to bring it up here to have an open discussion.

**Comment by gilesbradshaw** [comment]
I feel it would be good if any of the upcoming changes that can easily be implemented could be

**Comment by RickWong** [comment]
With Transmit, I'm trying my best to make it a Relay*ish* API that works without GraphQL. That's the most important goal. The current Transmit implementation supports only Promises, but I'm planning to support Streams and Observables as well (see https://github.com/RickWong/react-transmit/issues/25). That way more of the update/write functionality provided by Relay and GraphQL (see @josephsavona's comments in https://github.com/RickWong/react-transmit/issues/9) can be implemented with standard Javascript APIs that we're used to, know and love.

I think the main difference between Transmit and React-Resolver is that I have decided to follow the Relay API  and feature set closely. In that sense I'm restricted in terms of supporting other patterns. Transmit's server-side rendering is also very basic compared to React-Resolver's recursive component traversal etc.

So even if our projects' goals are similar, I believe it's a good thing to continue to explore different paths together. Fragmentation shouldn't be a huge issue as lots of people prefer to have more libraries to choose from, to find one that resonates well with their own projects.

**Comment by ericclemmons** [comment]
@RickWong Thanks for weighing in!  You've done fantastic work with Transmit, and I wanted to ensure as both projects progress, it's easier for users to know the key strengths/patterns/opinions in how they both work.

Admittedly, despite the API differences, on the surface they almost seem to be drop-in replacements for each other, which is why I questioned pursuing this project when yours has done so well.

Thanks again, and I hope to see you in http://reactiflux.com/ ! :)
