### ISSUE TITLE
Issue with nested routes (React Router 1.0)

### ISSUE THREAD

**Issue by srph** [ericclemmons/react-resolver#55]
I'm using React Router `v1.0.3`.

---

I'm trying this kind of route hierarchy:
```
-/ (top-level)
--/ (home page)
--/about (about page)
--/friends (/friends route top-level, fetching of friends)
----/ (friends index; /friends)
----/list (friends list; /friends/list)
```

<sub>(to code)</sub>

```jsx
      <Route path="friends" component={Friends}>
        <Route path="/" component={FriendsIndex} />
        <Route path="list" component={FriendsList} />
      </Route>
```

Where I am putting the Resolver container on the `friends` top-level component (`Friends`).

Here's the stack trace:
```
Uncaught (in promise) TypeError: Cannot read property 'ref' of undefined
    at cloneWithProps (http://localhost:1111/bundle.js:20673:13)
    at Friends.render (http://localhost:1111/bundle.js:23549:49)
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (http://localhost:1111/bundle.js:10462:34)
    at ReactCompositeComponentMixin._renderValidatedComponent (http://localhost:1111/bundle.js:10489:14)
    at ReactPerf.measure.wrapper (http://localhost:1111/bundle.js:16948:21)
    at ReactCompositeComponentMixin.mountComponent (http://localhost:1111/bundle.js:9910:30)
    at ReactPerf.measure.wrapper [as mountComponent] (http://localhost:1111/bundle.js:16948:21)
    at Object.ReactReconciler.mountComponent (http://localhost:1111/bundle.js:17763:35)
    at ReactCompositeComponentMixin._updateRenderedComponent (http://localhost:1111/bundle.js:10437:40)
    at ReactCompositeComponentMixin._performComponentUpdate (http://localhost:1111/bundle.js:10399:10)
```

Check this repo http://srph.github.io/rrt/#/friends

Not sure what I'm doing wrong haha.

**Comment by ericclemmons** [comment]
@srph Check out the example I have in `/examples`.  I'm using the latest React (v0.14) and _no container_, just normal `reactDOM.render(...)`.

If you can link the repo, that'd be great!

**Comment by srph** [comment]
I think I did link to the repo.. oh wait..  http://github.com/srph/rrt

**Comment by ericclemmons** [comment]
Ah, that's why:
> https://github.com/ericclemmons/react-resolver/blob/v2/examples/react-router/package.json#L15-L17

The _example_ is correct, but the actual project doesn't have that specified dep.

**Comment by ericclemmons** [comment]
Let's move the convo to #52, cool?

**Comment by srph** [comment]
I'm a bit confused. Mind clarifying?

Am I supposed to update? I'm using react-resolver 1.x which depends on React 0.13.

**Comment by ericclemmons** [comment]
Oh!  Whoops.  My mistake :)  Re-opening...

**Comment by srph** [comment]
Hmm, I'm still investigating at the moment. I removed react-resolver, and it seems that `this.props.children` is actually blank

**Comment by srph** [comment]
I'm reopening this. It seems that `this.props` isn't properly passed down to the component.

Check [`friends/list` route](http://srph.github.io/rrt/#/friends/list). It doesn't override the [default component set (`{this.props.children || <FriendsIndex />}`) to `friends` route](http://srph.github.io/rrt/#/friends) because it doesn't have any of the original props.

**Comment by srph** [comment]
Mind confirming if https://github.com/ericclemmons/react-resolver/blob/master/src/Container.js#L87 leads any clues?

**Comment by srph** [comment]
Hm.. haha, I feel stupid. Can you verify if the supposed component props are in the parent context (`this.context.parent`)?

**Comment by ericclemmons** [comment]
@srph Sorry, I'm at TXJS right now so a bit out of pocket.

Just so you know. React v0.13 makes context a complete PITA that gets worse when using other context-aware projects like React Router.

For this reason, I'm really focused on bringing over what our live project is using:
> https://github.com/ericclemmons/react-resolver/tree/v2/examples/react-router

- React v0.14
- React Router 1.0
- React Resolver v2

**Comment by srph** [comment]
Alright. Is it available through npm, or do I have to add the dependency through the repository link? I'll still take a look if v2 has solved this issue. I found out that the props aren't being passed over the the `component` prop or `children`.

The tests need a bit of refactoring.

**Comment by ericclemmons** [comment]
@srph Yep, I'll accept more PRs for v1.  I'm merging tons tonight!

**Comment by srph** [comment]
ALRIGHT :tada:  awesome, will send it tonight after work. Busy these days.

**Comment by ericclemmons** [comment]
Just learned last night that React Router v1.0.0-beta3 has *significant* server-side rendering bugs.  The v2 branch is a bit in flux because context is a PITA in React v0.13, and React Router v0.13.3 is the most stable one we have.

**Comment by ericclemmons** [comment]
@srph I got tons of examples working in v2 (just launched!)  This _should_ be resolved, but feel free to open if it indeed is not.
