### ISSUE TITLE
Symbol is not defined

### ISSUE THREAD

**Issue by ericclemmons** [ericclemmons/react-resolver#58]
@goatslacker Didn't you stop using `Symbol` in Alt?  What was the reason behind that again?

It works pretty well with anything using the Babel Polyfill, but with ES5 users in mind, should I just drop it & use local constants instead?

**Comment by goatslacker** [comment]
Yeah I dropped Symbol from Alt on v0.17 mostly because I didn't want to include the polyfill. Symbol can't be correctly polyfilled and the babel polyfill for Symbol wasn't the one I was including for reasons so there weren't a lot of advantages to be had.

**Comment by ericclemmons** [comment]
@goatslacker Thanks!  Glad I dropped it then.

Let me know of any other tricks you pick up on I should copy ;)
