### ISSUE TITLE
Not all Promises are created equal

### ISSUE THREAD

**Issue by iamdustan** [ericclemmons/react-resolver#64]
Currently the Resolver tests that a `@resolve` Promise is `instanceof Promise`. Promises seem to be a bit fickle in that there are many different implementations and ways to get a global Promise object.

A few possibilities:

* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise
* https://github.com/petkaantonov/bluebird
* https://github.com/kriskowal/q
* http://api.jquery.com/jquery.ajax/ / http://api.jquery.com/category/deferred-object/
* https://github.com/jakearchibald/es6-promise
* https://www.npmjs.com/package/core-js#ecmascript-6-promises

The question is should we expect one global Promise object or provide a duckpunch to interop with the different methods?

Alternatively, we could ignore Promises and use a callback which the consumer is responsible for calling in whatever async control flow implementation they should choose.

**Comment by ericclemmons** [comment]
This is being resolved in #65 .
