### ISSUE TITLE
Examples need a build step

### ISSUE THREAD

**Issue by ostrgard** [ericclemmons/react-resolver#66]
Both examples is missing a `client.min.js` build and express handling of requests to this file.

... or am I missing somthing?

**Comment by ericclemmons** [comment]
@ostrgard Whoops, I'll put something in their READMEs.

Do `npm run watch` for now.  With the refactor I forgot to update their docs & put in a proper build step for a plain `npm start`.

> https://github.com/ericclemmons/react-resolver/blob/master/examples/react-v0.13/package.json#L7

**Comment by ostrgard** [comment]
Alright! I'm having an issue with react-router and react-resolver that I can't test in your examples without the build step. I'm writing separate issue on that right now though.

Thank you for the quick response!

**Comment by ericclemmons** [comment]
With `v2.0.3` these examples have a README with steps:
> https://github.com/ericclemmons/react-resolver/tree/master/examples/react-v0.13

Basically, `npm start` for dev, and `NODE_ENV=production npm start` for the build step.
