### ISSUE TITLE
Routes break after clicking first link

### ISSUE THREAD

**Issue by jachenry** [ericclemmons/react-resolver#75]
I have an issue where the client side routes break after navigating to a single link. From then on the path changes in the address bar but nothing gets updated on the screen. All the Handlers are returning standard React components without wrapping with Resolvers. 

package.json
```
    "react": "0.13.3",
    "react-router": "0.13.3",
    "react-resolver": "^2.0.4",
    "react-router-server-location": "^2.0.0",
```

Routes.js
```jsx
	<Route path="/" handler={Main}>
		<DefaultRoute handler={Home} />
		<Route name="signin" path="/signin" handler={Signin}/>
		<Route name="signup" path="/signup" handler={Signup}/>
 		<Route name="forgot_password" path="/users/password" handler={ForgotPassword}/>
		<Route name="reset_password" path="/users/password/edit" handler={ResetPassword}/>
		<Route name="account" path="/account/profile" handler={AccountNavigation}>
			<DefaultRoute name="account_profile" handler={AccountProfile} />
			<Route name="account_settings" path="/account/settings" handler={AccountSettings} />
		</Route>
	</Route>
```

client.js
```
Router.run(routes, Router.HistoryLocation, (Root) => {
	Resolver.render(() => <Root />, document.getElementById("react-root"));
});
```

**Comment by ericclemmons** [comment]
Thanks for the detailed report!

I think I'll have to create a "plain" example as you've described with no `@resolve` decorators to replicate this.

Which means, there's also no need for you to do `Resolver.render` then, since there's nothing to resolve.  `React.render(<Root />)` will suffice.

Are there _any_ errors in your console at all?

**Comment by jachenry** [comment]
Switching to `React.render(...)` solved the issue while still giving me access to the router state in props.

```
Router.run(routes, Router.HistoryLocation, (Root) => {
	React.render(<Root />, document.getElementById("react-root"))
	//Resolver.render(() => <Root />, document.getElementById("react-root"));
});
```

**Comment by ericclemmons** [comment]
@jachenry Let me know if everything goes back to normal once you start decorating components.

I'm re-opening because this is an edge-case that I still find peculiar...

**Comment by ericclemmons** [comment]
Actually, this looks related to #78.

It's a regression.  Thanks for letting me know!

**Comment by bbnnt** [comment]
Where is the regression happening ?

**Comment by ericclemmons** [comment]
I'll be working on this stuff today.

**Comment by ericclemmons** [comment]
To be honest, I can't figure out how this is an issue with the Resolver & can only confirm it's an issue with React Router v0.13.3:

> ![router](https://cloud.githubusercontent.com/assets/15182/9706587/bc092daa-54ae-11e5-8d16-face8b2037bf.gif)

It's not a problem with React Router v1.0.0-beta3:
> ![14](https://cloud.githubusercontent.com/assets/15182/9706589/cc716e32-54ae-11e5-966a-423c663bb4d8.gif)

I just opened rackt/react-router#1833 for help on this & will re-open this issue as needed...
