### ISSUE TITLE
Cannot find module 'babel/register'

### ISSUE THREAD

**Issue by bbnnt** [ericclemmons/react-resolver#77]
Sorry to bother on this one;
I was interested in your tool, without being able to run the examples, stuck with the following error : 

```
[piping] can't execute file: /Users/xx/Desktop/react-resolver/examples/react-v0.13/watch.js
[piping] error given was: Error: Cannot find module 'babel/register'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.module._load (/Users/xx/Desktop/react-resolver/examples/react-v0.13/node_modules/piping/lib/launcher.js:24:23)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/xx/Desktop/react-resolver/examples/react-v0.13/src/server.js:1:63)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Module._load (module.js:310:12)
    at Function.module._load (/Users/xx/Desktop/react-resolver/examples/react-v0.13/node_modules/piping/lib/launcher.js:32:16)
[piping] further repeats of this error will be suppressed...
```

I wonder if that would be an easy answer;
thanks for your time

**Comment by ericclemmons** [comment]
@bbnnt Within those example directories did you run `npm install` & `npm start`?

**Comment by bbnnt** [comment]
sure did; won't say I'm expert in react and the ecosystem, but I've understood how webpack works, how to use package.json, etc… the basic architecture of those tools.

But never seen any examples using this piping thing, I was expecting to be lucky if this one sounded obvious for you

**Comment by ericclemmons** [comment]
@bbnnt Sorry, I didn't mean to make it seem like you didn't know.  Someone brought up the docs for the examples once before & I was hoping it was the same here.

Reason being, I just did a `git clean -fdx. && npm start` within the example & had it running:
> ![example](https://cloud.githubusercontent.com/assets/15182/9560109/a2edece8-4dc9-11e5-98c3-1c9d0973316e.gif)

Although now I fear there's a regression with `HistoryLocation` :(

**Comment by bbnnt** [comment]
No problem, I was just in hope to find out and understand things better hacking with your examples.

Damn it, being a "server-side-dev", I'm was looking for a clean way to get into isomorphism. so far I was pretty disapointed with what exists in the ecosystem; but have to say your tool is perfect (doing data call from within the components, I just don't understand why it is not a main concern in react and why isomorphism got so big without actually providing a solid pattern for it)

Could it come from my node version maybe ? Mine is v0.12.6

**Comment by ericclemmons** [comment]
That's really bizarre!   Do you have babel installed globally?  `npm run` commands automatically path `node_modules/.bin` from the local install, but globals still take precedent.

**Comment by bbnnt** [comment]
Too bad for the examples, but I gave it up; wasn't a big deal
In any cases I managed to use your project as intended ! #76 seems more important in any cases

**Comment by ericclemmons** [comment]
Sorry it didn't work out.  Truthfully, it sounds more like the `npm install` messed up on your machine.

**Comment by jasonphillips** [comment]
A clarification on this one:  I ran into it as well on a clean installation of the example folder. 

It appears that the issue is simply that `src/server.js` calls `require(babel/register)`, while the package.json for the example installs `babel-core` instead of `babel`. 

It will function nonetheless if you have already run `npm install` in the root of the react-resolver project, because there `babel` is installed and the require statement from the example will find it in that parent folder. 

The fix to make the example work independently as designed is simply to require `babel-core/register` instead of `babel/register` in server.js, since that is the module it installs. This fix should avert the issue for others who run into this simple roadblock by running the example on its own.

**Comment by ericclemmons** [comment]
Ah, and you answered it here.  Thanks :)

**Comment by bbnnt** [comment]
well not sure if it was updated or not, but it does not work !
thx

**Comment by ericclemmons** [comment]
Yay, thanks @jasonphillips!
