### ISSUE TITLE
Update react-router example

### ISSUE THREAD

**Issue by geekyme** [ericclemmons/react-resolver#87]
In the newest react-router, the server side rendering and client side rendering has changed a lot so I'm no longer sure of how to use <Resolver>. Would love to get some help in terms of an updated example for react-router.

**Comment by geekyme** [comment]
Took a stab at trying to integrate the library. https://github.com/gpbl/redux500/tree/new-rr

At the moment i'm running into problems 

```
Warning: owner-based and parent-based contexts differ (values: `undefined` vs `[object Object]`) for key (resolver) while mounting Resolver (see: http://fb.me/react-context-by-parent)
```

**Comment by geekyme** [comment]
in addition, the page also makes another similar XHR call on the client side even after a full page reload (server already made the XHR call)

**Comment by aripalo** [comment]
Here's how I have gotten react-resolver to work with server-side rendering with `react-router@1.0.0-rc3`:

```js
// run the router
match({ routes, location: req.url }, (error, redirectLocation, renderProps) => {

  // Redirected wanted
  if (redirectLocation) {
    //handle redirect

  // Some error happened
  if (error) {
    //handle error
  }

  // No renderProps -> no route matched -> 404
  // See: https://github.com/rackt/react-router/blob/master/docs/guides/advanced/ServerRendering.md#server-rendering
  if(renderProps == null) {
    //handle 404
  }

  // resolve data before rendering components
  Resolver
    .resolve(() => <Provider store={store}><RoutingContext {...renderProps}/></Provider>)
    .then(({ Resolved, data }) => {

      // render the react app into string (which is passed into index template)
      const markup = ReactDOMServer.renderToStaticMarkup(<Resolved />);

      // 
      const bootstrapData = JSON.stringify(data);

      // send the markup and bootstrapData to your server side template etc
      res
        .status(200)
        .render('index', {
          markup,
          JSON.stringify(data),
        });

    })
    .catch((error) => {
      // handle error
    });

});
```

... but haven't yet figured out how to handle the client-side

**Comment by p-ho** [comment]
I've also got some problems figuring the right approach for client-side.
Currently, I use the following:
```jsx
Resolver.render(() => (
  <Router history={createHistory()}>{routes}</Router>
), document.getElementById('myapp'));
```

It works, but the Resolver injects a `noscript`-Element into the container - for no obvious reason.
Which results in the well known warning:
```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) <noscript data-reacti
 (server) <div id="myapp
```

**Comment by ericclemmons** [comment]
It looks like the client isn't initialized with a payload for it to render synchronously.

(That's why there's a <noscript> on the client & the server renders fine)

Otherwise, do you have a sample of your `client.js`?

**Comment by p-ho** [comment]
@ericclemmons You're right, actually the payload was missing. I forgot the `async` and `defer` attributes for my client.js. Therefore the payload hadn't been initialized at execution time.
thx for the little advice.

**Comment by chibicode** [comment]
I also got stuck as the [documentation](http://ericclemmons.com/react-resolver/docs/getting-started/ServerRendering.html) is using outdated react-router api (currently at 2.6.x now, but the doc seems to be < 1.0).

I also tried out a similar library called redial, and its documentation seems to be current, so maybe react-resolver's doc can borrow some ideas from it:
https://github.com/markdalgleish/redial#example-server-usage

**Comment by ericclemmons** [comment]
Yea, this could definitely use a newer `react-router` example!

**Comment by bergkampho** [comment]
@p-ho I got the same problem in `client.js`. Could you provide some sample code for adding `async` and `defer` attributes?

**Comment by p-ho** [comment]
@bergkampho 

The relevant HTML parts (ES6-template):
```html
    <body>
        <div id="outerMainAppContainer">${content}</div>
        <script src="${jsBundlePath}" async defer></script>
        <script>window.__REACT_RESOLVER_PAYLOAD__ = ${reactResolverPayload};</script>
    </body>
```

The relevant JS parts (I use react-router):
```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import {Resolver} from 'react-resolver';
import {Router, browserHistory} from 'react-router';
[...]

Resolver.render(() => (
        <Router history={browserHistory}>{routes}</Router>
), document.getElementById('outerMainAppContainer'));
```

**Comment by monder** [comment]
https://github.com/ericclemmons/react-resolver/commit/295a8904661c82b5929e51c7ee029f7d55af5989
Added example with
- `express` (v4.14.0)
- `react` (v15.3.0)
- `react-dom` (v15.3.0)
- `react-router` (v2.6.1)
