### ISSUE TITLE
Test out react-router-component

### ISSUE THREAD

**Issue by ericclemmons** [ericclemmons/react-resolver#9]
This looks like a cleaner implementation:
> https://github.com/STRML/react-router-component

**Comment by adri** [comment]
👍 for react-router-component (or in general being able to choose a router)

**Comment by ericclemmons** [comment]
If I can figure out how the heck to test out `peerDependencies` (and `optionalDependencies`), I might be able to get rid of the `react-router` requirement!

**Comment by adri** [comment]
If the `react-router` is not used within react-resolver, why would you then even provide a router as `peerDependency` (or `optionalDependency`)?

Would it be feasible to create a wrapping/higher-order component (like described in #8) which sets the `context`? This component could then be used by a user of react-resolve to wrap around the `App` component.

**Comment by ericclemmons** [comment]
It's a requirement for maintaining contexts when using `react-router`:
> https://github.com/ericclemmons/react-resolver/blob/a6dba1173636107404b3f5c3ea13287d8d50ed3f/lib/resolver.js#L36

At the time of inception, this was necessary for server-side rendering with `react-router`.

The goal would be, if this remains in, being able to have an optional dependency on it in the consumer project.

I can try replacing this with a wrapping component that's _not_ a route, but I could've sworn I had to use a `<Route />`...

**Comment by ericclemmons** [comment]
Oh!  But related to #10, I still need to set `react` as one of the `peerDependencies`, but I can't for the life of me figure out how to confirm this behavior w/o tagging & releasing & testing with a new project!

**Comment by adri** [comment]
I really like where this project is going.

> The goal would be, if this remains in, being able to have an optional dependency on it in the consumer project.

If it's used I suppose its not optional ;-) 

As far as I see the [`<Route />`](https://github.com/ericclemmons/react-resolver/blob/a6dba1173636107404b3f5c3ea13287d8d50ed3f/lib/resolver.js#L36) is basically a wrapper around the outmost (highes level) route handler from the user. The neat thing about extracting the `context` initialization in a wrapping component is, that react-router can then be used with any router (or none) out of the box.

**Comment by ericclemmons** [comment]
I'll be testing out `react-router`'s stringent-ness on this :)  Hopefully I can warp it in something _other than_ a `<Route />`.

**Comment by ericclemmons** [comment]
Not necessary anymore with [v1.0.0](d7c9d843e091700f0c3f61843f8f3e8bfd707f64).
