### ISSUE TITLE
Sequential resolving

### ISSUE THREAD

**Issue by khankuan** [ericclemmons/react-resolver#92]
Any thoughts if sequential mode is useful? (vs Promise.all)

**Comment by khankuan** [comment]
Maybe an option for the child components depends on the parent's to resolve before continuing. Is it the current behaviour already?

**Comment by ericclemmons** [comment]
```
@resolve("foo", ...)
@resolve("bar", ...)
@resolve({
  baz: ...,
  bing: ...
})
class FooBarBazBing ...
```

This already works now & is good for optimizing requests.

**Comment by khankuan** [comment]
Ah awesome!

**Comment by ericclemmons** [comment]
:)
