### ISSUE TITLE
Context availability 

### ISSUE THREAD

**Issue by khankuan** [ericclemmons/react-resolver#95]
For the resolve method, can context be passed in as a input? Probably handy in situations that needs context.

**Comment by ericclemmons** [comment]
There's a `@context` decorator that's useful for this:

```js
@context("router")
@resolve("query", ({ router }) => router.query)
class QueryViewer ...
```

The only context that the HoCs get are the ones defined somehow.  So, by default, they'd only have access to `resolver`.

**Comment by khankuan** [comment]
Ah nice! Probably would be clearer when docs is up :+1:
