### ISSUE TITLE
Initial rendering 

### ISSUE THREAD

**Issue by khankuan** [ericclemmons/react-resolver#96]
Is there a way to turn of resolving totally. What happens is the react router was having empty route handlers because of the resolve. Resolving immediately doesn't work as well since it is executed after router is done. This causes universal rendering checksum to mismatch.

**Comment by ericclemmons** [comment]
I'm not sure what problem you're having without showing some code.

I render on the server & bootstrap on the client w/o checksum issues, including using React Router.

**Comment by khankuan** [comment]
Ah, i was returning Promise.resolve() instead of return.. thats probably the cause. Thanks!

**Comment by khankuan** [comment]
Hmm quick question: Is it possible to prevent resolve from running at initial render on client side? I might be able to do it by setting a window variable and checking it but that might not be so nice in code :P

**Comment by ericclemmons** [comment]
You can do a normal `React.render(<Whatever />, mountNode)` and skip the resolving part.

But, really, as long as the props are already set, resolver won't do squat :D

**Comment by khankuan** [comment]
Hmm odd,  I tried that and had the same result as resolver

**Comment by ericclemmons** [comment]
Well, the @resolve decorators are still there.  So either the data exists via props, or is in the resolver cache that you provide :)
